/*
 * Copyright (c) 2016 Libsquash contributers
 *
 * This file is part of libsquash, distributed under the MIT License
 * For full terms see the included LICENSE file
 */

#ifndef SQUASH_H_256A1657
#define SQUASH_H_256A1657

#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <sys/stat.h>

#include "squash/version.h"
#include "squash/error.h"
#include "squash/types.h"

/* 
 * squash_opendisk(error, data, data_size)
 *
 * Opens a SquashFS disk by reading the memory at data up to data_size bytes.
 * data should point to an array of bytes of a SquashFS file,
 * which could be generated by an independently installed mksquashfs tool
 * and be loaded into memory in advance.
 * If successful, squash_opendisk() returns a pointer to the disk;
 * otherwise NULL is returned and error is set to the reason of the error.
 * The returned disk should later be closed by squash_closedisk().
 */
squash_disk_t *squash_opendisk(squash_error_t * error, const uint8_t * data,
			       size_t data_size);

/* 
 * squash_closedisk(error, disk)
 *
 * Closes the named SquashFS disk and frees the structures associated with it.
 * Note that the original referenced array of bytes of a SquashFS file
 * will not be freed.
 * Upon successful completion, a value of 0 is returned.
 * Otherwise, a value of -1 is returned and error is set to
 * the reason of the error.
 */
int squash_closedisk(squash_error_t * error, squash_disk_t * disk);

/* 
 * squash_stat(error, disk, path, buf)
 *
 * Obtains information about the file pointed to by path of a SquashFS disk.
 * The buf argument is a pointer to a stat structure as defined by
 * <sys/stat.h> and into which information is placed concerning the file.
 * Upon successful completion a value of 0 is returned.
 * Otherwise, a value of -1 is returned and error is set to
 * the reason of the error.
 */
int squash_stat(squash_error_t * errno, squash_disk_t * disk, const char *path,
		struct stat *buf);

/* 
 * squash_lstat(error, disk, path, buf)
 *
 * Acts like squash_stat() except in the case where the named file
 * is a symbolic link; squash_lstat() returns information about the link,
 * while squash_stat() returns information about the file the link references.
 */
int squash_lstat(squash_error_t * errno, squash_disk_t * disk, const char *path,
		 struct stat *buf);

/* 
 * squash_fstat(error, disk, fildes, buf)
 *
 * Obtains the same information as squash_stat() about an open file
 * known by the Libsquash file descriptor fildes.
 */
int squash_fstat(squash_error_t * errno, squash_disk_t * disk, int fildes,
		 struct stat *buf);

#endif
